from unsloth import FastLanguageModel
import torch
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments


def train():
    # --- Configuration ---
    # Model Choice
    # model_name = "unsloth/Llama-3.3-70B-Instruct-bnb-4bit"
    model_name = "unsloth/Qwen2.5-72B-Instruct-bnb-4bit"

    # H200 allows for much larger context. Legal docs benefit from this.
    max_seq_length = 8192
    dtype = None  # Auto detection (Float16/Bfloat16)
    load_in_4bit = True

    # --- 1. Load Model ---
    print(f"Loading model: {model_name}...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_name,
        max_seq_length=max_seq_length,
        dtype=dtype,
        load_in_4bit=load_in_4bit,
    )

    # --- 2. Add LoRA adapters ---
    model = FastLanguageModel.get_peft_model(
        model,
        r=16,  # Rank 16 is sufficient for style/domain adaptation
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],
        lora_alpha=16,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
        use_rslora=False,
        loftq_config=None,
    )

    # --- 3. Load Data ---
    # Ensure this points to the correct path generated by your pipeline
    dataset_path = "training_data.jsonl"
    print(f"Loading dataset from {dataset_path}...")

    # Check if chat template is needed
    from unsloth.chat_templates import get_chat_template

    # tokenizer = get_chat_template(tokenizer, chat_template="llama-3")
    tokenizer = get_chat_template(tokenizer, chat_template="qwen-2.5")

    def formatting_prompts_func(examples):
        convos = examples["messages"]
        texts = [
            tokenizer.apply_chat_template(
                convo, tokenize=False, add_generation_prompt=False
            )
            for convo in convos
        ]
        return {
            "text": texts,
        }

    try:
        dataset = load_dataset("json", data_files=dataset_path, split="train")
    except Exception as e:
        print(f"Error loading dataset: {e}")
        # Fallback for testing/dev if file doesn't exist
        print(
            "WARNING: Could not load real dataset. Create 'training_data.jsonl' first."
        )
        return

    # Perform 95/5 Train/Val split (Dataset is 5000+, 5% is ~250 val samples)
    dataset = dataset.train_test_split(test_size=0.05)

    dataset["train"] = dataset["train"].map(formatting_prompts_func, batched=True)
    dataset["test"] = dataset["test"].map(formatting_prompts_func, batched=True)

    print(f"Train size: {len(dataset['train'])}, Test size: {len(dataset['test'])}")

    # --- 4. Train ---
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset["train"],
        eval_dataset=dataset["test"],
        dataset_text_field="text",
        max_seq_length=max_seq_length,
        dataset_num_proc=4,  # Parallel processing
        packing=False,
        args=TrainingArguments(
            per_device_train_batch_size=4,  # Adjust based on 8192 context fits. H200 is huge so 4 should be fine.
            gradient_accumulation_steps=4,  # Effective batch size = 4*4 = 16
            warmup_steps=100,
            num_train_epochs=1,  # Use epochs for full dataset coverage
            learning_rate=2e-4,
            fp16=not torch.cuda.is_bf16_supported(),
            bf16=torch.cuda.is_bf16_supported(),
            logging_steps=10,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="linear",
            seed=3407,
            output_dir="checkpoints",
            # careful saving logic
            save_strategy="epoch",
            save_total_limit=2,  # Keep only last 2 checkpoints
            # evaluation
            eval_strategy="steps",
            eval_steps=200,  # Evaluate every 200 steps
            per_device_eval_batch_size=2,
            report_to="none",  # Set to 'wandb' if you have it
        ),
    )

    trainer.train()

    # --- 5. Save ---
    print("Saving final model...")
    model.save_pretrained("lora_model")
    tokenizer.save_pretrained("lora_model")
    # Also save to GGUF if needed (commented out by default)
    # model.save_pretrained_gguf("lora_model_gguf", tokenizer, quantization_method = "q4_k_m")


if __name__ == "__main__":
    train()
